"""
REST API for the Detection Engine (Member 2's handoff to Member 3).

Run it with:
    uvicorn api:app --reload

Then open http://127.0.0.1:8000/docs for interactive API docs
(auto-generated by FastAPI — great for demoing to judges).
"""

from datetime import datetime
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from detection_engine import DetectionEngine, LogEvent, SEVERITY_MEANINGS

app = FastAPI(
    title="Detection Engine API",
    description="Rule-based detection, severity calculation, alert generation, "
                 "and safe simulated response for the hackathon prototype.",
    version="1.0.0",
)

# Allow the frontend dashboard (served from a different port, e.g. Live Server
# on 5500) to call this API. See Member 3 spec section 8.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://127.0.0.1:5500",
        "http://localhost:5500",
        "http://127.0.0.1:8080",
        "http://localhost:8080",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Single shared engine instance for the life of the server (in-memory storage).
# Swap this for a DB-backed engine later without changing the routes below.
engine = DetectionEngine()


# ---------------------------------------------------------------------------
# Request/response schemas
# ---------------------------------------------------------------------------
class EventIn(BaseModel):
    event_type: str = Field(..., examples=["LOGIN_FAILURE", "LOGIN_SUCCESS"])
    source_ip: str = Field(..., examples=["10.0.0.25"])
    timestamp: Optional[datetime] = Field(
        default=None,
        description="Defaults to now if omitted",
    )
    username: Optional[str] = None


class ThreatIntelIndicator(BaseModel):
    indicator: str
    indicator_type: str
    confidence: str
    source: str


class ThreatIntelImport(BaseModel):
    indicators: List[ThreatIntelIndicator]


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.post("/events", summary="Ingest a structured log event")
def ingest_event(event_in: EventIn):
    """
    Step 1 of the detection flow: receive a structured log event
    (normally sent by Member 1's ingestion layer). Runs all rules
    and returns any alerts generated by this single event.
    """
    event = LogEvent(
        event_type=event_in.event_type,
        source_ip=event_in.source_ip,
        timestamp=event_in.timestamp or datetime.now(),
        username=event_in.username,
    )
    new_alerts = engine.process_event(event)
    return {
        "received": event.to_dict(),
        "alerts_generated": [a.to_dict() for a in new_alerts],
    }


@app.get("/alerts", summary="List all alerts")
def list_alerts(severity: Optional[str] = None, status: Optional[str] = None):
    """
    What Member 3's dashboard polls/fetches. Optional filters by
    severity (LOW/MEDIUM/HIGH/CRITICAL) and status (OPEN/etc).
    """
    alerts = engine.get_alerts()
    if severity:
        alerts = [a for a in alerts if a["severity"] == severity.upper()]
    if status:
        alerts = [a for a in alerts if a["status"] == status.upper()]
    return alerts


@app.get("/alerts/{alert_id}", summary="Get a single alert by ID")
def get_alert(alert_id: str):
    for a in engine.get_alerts():
        if a["alert_id"] == alert_id:
            return a
    raise HTTPException(status_code=404, detail="Alert not found")


@app.get("/responses", summary="List all simulated response audit records")
def list_responses():
    return engine.get_responses()


@app.get("/severity-meanings", summary="LOW/MEDIUM/HIGH/CRITICAL definitions")
def severity_meanings():
    """For Member 3's dashboard to explain severity colors/labels to users."""
    return SEVERITY_MEANINGS


@app.post("/threat-intel/import", summary="Import indicators from Member 4")
def import_threat_intel(payload: ThreatIntelImport):
    engine.import_threat_intel([i.model_dump() for i in payload.indicators])
    return {"imported": len(payload.indicators), "total_indicators": len(engine.threat_intel)}


@app.get("/threat-intel", summary="List currently loaded threat-intel indicators")
def list_threat_intel():
    return list(engine.threat_intel.values())


@app.get("/health", summary="Health check (Member 3 API contract)")
def health():
    return {
        "status": "ok",
        "alerts_count": len(engine.alerts),
        "responses_count": len(engine.responses),
    }


@app.get("/stats", summary="Dashboard counters (Member 3 API contract)")
def stats():
    """
    Powers Member 3's Dashboard page: total logs, total alerts,
    high/critical alerts, threat-intel count, recent events.
    """
    return engine.get_stats()


@app.get("/logs", summary="Recent ingested log events (Member 3 API contract)")
def logs(limit: int = 50):
    return engine.get_logs(limit=limit)


@app.get("/reports/{report_id}", summary="Human-readable incident report (Member 3 API contract)")
def get_report(report_id: str):
    report = engine.get_report(report_id)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return report


@app.get("/", summary="Root — points to the docs")
def root():
    return {"message": "Detection Engine API is running. See /docs for endpoints."}
