"""
Detection Engine, Alerts & Safe Response
(Member 2's deliverable)

Turns structured log events into explainable alerts and creates an
auditable, SIMULATED response record for each one. Never touches the
real OS, firewall, accounts, or network (see section 6 of the spec).
"""

from collections import defaultdict
from datetime import timedelta
from typing import Dict, List, Optional

from .config import load_config
from .models import Alert, LogEvent, ResponseRecord

# --- Severity levels, for reference / Member 3 handoff (section 10) -------
SEVERITY_MEANINGS = {
    "LOW": "Informational. No immediate action needed; useful for trend analysis.",
    "MEDIUM": "Unusual but not confirmed malicious. Analyst review recommended.",
    "HIGH": "Strong evidence of an attack pattern. Simulated containment triggered.",
    "CRITICAL": "Confirmed malicious indicator match. Immediate simulated isolation.",
}

# --- Response action -> audit description template (section 6) ----------
RESPONSE_TEMPLATES = {
    "BLOCK_IP_SIMULATED": "IP {source_ip} marked as blocked in response policy",
    "FLAG_FOR_REVIEW": "Event added to analyst review queue",
    "ISOLATE_HOST_SIMULATED": "Host isolation recommended and recorded",
}

# --- Demo response action per rule ---------------------------------------
RULE_RESPONSE_ACTION = {
    "RULE-001": "BLOCK_IP_SIMULATED",
    "RULE-002": "FLAG_FOR_REVIEW",
    "RULE-003": "ISOLATE_HOST_SIMULATED",
}


class DetectionEngine:
    def __init__(self, config_path: Optional[str] = None, threat_intel: Optional[dict] = None):
        self.config = load_config(config_path) if config_path else load_config()

        # source_ip -> list of LoginFailure timestamps (step 2/3 of the flow)
        self._failed_login_history: Dict[str, List] = defaultdict(list)

        # Prevents duplicate alerts for the same burst (spec step 8).
        # Tracks the most recent burst-window end time we already alerted on, per IP.
        self._last_alerted_window_end: Dict[str, "object"] = {}

        # indicator (source_ip) -> record, provided/imported by Member 4
        self.threat_intel: Dict[str, dict] = threat_intel or {}

        self.alerts: List[Alert] = []
        self.responses: List[ResponseRecord] = []

        # Every log event ever received, for Member 3's /logs and /stats.
        self.all_events: List[LogEvent] = []

    # ------------------------------------------------------------------
    # Threat intel import (handoff to Member 4, section 11 / 7)
    # ------------------------------------------------------------------
    def import_threat_intel(self, indicators: List[dict]) -> None:
        """
        Each indicator dict must have: indicator, indicator_type,
        confidence, source (the minimum fields agreed with Member 4).
        """
        for item in indicators:
            required = {"indicator", "indicator_type", "confidence", "source"}
            missing = required - item.keys()
            if missing:
                raise ValueError(f"threat intel indicator missing fields: {missing}")
            self.threat_intel[item["indicator"]] = item

    def is_known_malicious(self, source_ip: str) -> bool:
        """Section 7: 'Does this source IP exist in the local threat-intel table?'"""
        return source_ip in self.threat_intel

    # ------------------------------------------------------------------
    # Main entry point — implements the 8-step detection flow (section 4)
    # ------------------------------------------------------------------
    def process_event(self, event: LogEvent) -> List[Alert]:
        """
        Step 1: receive a structured log event (the `event` argument).
        Steps 2-8 happen here. Returns any alerts generated by this event
        (usually 0 or 1).
        """
        new_alerts: List[Alert] = []
        self.all_events.append(event)

        # RULE-003 first: a single event against a known-bad IP is CRITICAL
        # regardless of behavioral pattern.
        intel_alert = self._check_threat_intel_rule(event)
        if intel_alert:
            new_alerts.append(intel_alert)

        if event.event_type == "LOGIN_FAILURE":
            failed_login_alert = self._check_failed_login_rule(event)
            if failed_login_alert:
                new_alerts.append(failed_login_alert)

        if event.event_type in ("LOGIN_SUCCESS", "LOGIN_FAILURE"):
            odd_hours_alert = self._check_odd_hours_rule(event)
            if odd_hours_alert:
                new_alerts.append(odd_hours_alert)

        # Step 6: create a response record for every alert generated.
        for alert in new_alerts:
            self._create_response(alert)

        return new_alerts

    # ------------------------------------------------------------------
    # RULE-001: 5+ failed logins from same IP within 5 minutes -> HIGH
    # ------------------------------------------------------------------
    def _check_failed_login_rule(self, event: LogEvent) -> Optional[Alert]:
        ip = event.source_ip
        window = timedelta(minutes=self.config["failed_login_window_minutes"])
        threshold = self.config["failed_login_threshold"]

        # Step 2/3: track and count matching events inside the window.
        history = self._failed_login_history[ip]
        history.append(event.timestamp)
        history.sort()

        window_start = event.timestamp - window
        recent = [t for t in history if t > window_start]
        self._failed_login_history[ip] = recent

        # Step 4: threshold check.
        if len(recent) < threshold:
            return None

        # Step 8: de-duplicate — don't re-alert for the same burst.
        # A "burst" is identified by its window; once alerted, we require
        # the oldest event in the window to move past the previous
        # trigger point before alerting again.
        burst_start = min(recent)
        already_alerted = self._last_alerted_window_end.get(ip)
        if already_alerted is not None and burst_start <= already_alerted:
            return None
        self._last_alerted_window_end[ip] = event.timestamp

        # Steps 5 & 7: assign severity + explanation, create the alert.
        reason = (
            f"{len(recent)} failed logins from the same IP "
            f"within {self.config['failed_login_window_minutes']} minutes"
        )
        alert = Alert(
            rule_id="RULE-001",
            title="Repeated failed login attempts",
            severity="HIGH",
            source_ip=ip,
            reason=reason,
        )
        self.alerts.append(alert)
        return alert

    # ------------------------------------------------------------------
    # RULE-002: login outside configured normal hours -> MEDIUM
    # ------------------------------------------------------------------
    def _check_odd_hours_rule(self, event: LogEvent) -> Optional[Alert]:
        hour = event.timestamp.hour
        start = self.config["normal_login_start"]
        end = self.config["normal_login_end"]

        if start <= hour < end:
            return None  # inside normal hours -> no alert

        reason = (
            f"Login at {event.timestamp.strftime('%H:%M')} falls outside "
            f"configured normal hours ({start:02d}:00-{end:02d}:00)"
        )
        alert = Alert(
            rule_id="RULE-002",
            title="Login outside normal hours",
            severity="MEDIUM",
            source_ip=event.source_ip,
            reason=reason,
        )
        self.alerts.append(alert)
        return alert

    # ------------------------------------------------------------------
    # RULE-003: known malicious indicator from threat-intel list -> CRITICAL
    # ------------------------------------------------------------------
    def _check_threat_intel_rule(self, event: LogEvent) -> Optional[Alert]:
        if not self.is_known_malicious(event.source_ip):
            return None

        indicator = self.threat_intel[event.source_ip]
        reason = (
            f"Source IP matches known malicious indicator "
            f"(source: {indicator['source']}, confidence: {indicator['confidence']})"
        )
        alert = Alert(
            rule_id="RULE-003",
            title="Known malicious indicator match",
            severity="CRITICAL",
            source_ip=event.source_ip,
            reason=reason,
        )
        self.alerts.append(alert)
        return alert

    # ------------------------------------------------------------------
    # Safe, simulated response (section 6)
    # ------------------------------------------------------------------
    def _create_response(self, alert: Alert) -> ResponseRecord:
        action = RULE_RESPONSE_ACTION[alert.rule_id]
        description = RESPONSE_TEMPLATES[action].format(source_ip=alert.source_ip)
        record = ResponseRecord(
            alert_id=alert.alert_id,
            action=action,
            description=description,
        )
        self.responses.append(record)
        return record

    # ------------------------------------------------------------------
    # Convenience accessors for the API layer (Member 3)
    # ------------------------------------------------------------------
    def get_alerts(self) -> List[dict]:
        return [a.to_dict() for a in self.alerts]

    def get_responses(self) -> List[dict]:
        return [r.to_dict() for r in self.responses]

    def get_logs(self, limit: int = 50) -> List[dict]:
        """Most recent events first — for Member 3's /logs page."""
        recent = sorted(self.all_events, key=lambda e: e.timestamp, reverse=True)
        return [e.to_dict() for e in recent[:limit]]

    def get_stats(self) -> dict:
        """Powers Member 3's Dashboard page (section 3 of their spec)."""
        alerts = self.get_alerts()
        high_critical = [a for a in alerts if a["severity"] in ("HIGH", "CRITICAL")]
        return {
            "total_logs": len(self.all_events),
            "total_alerts": len(alerts),
            "high_critical_alerts": len(high_critical),
            "threat_intel_count": len(self.threat_intel),
            "recent_events": self.get_logs(limit=10),
        }

    def get_report(self, alert_id: str) -> Optional[dict]:
        """
        Human-readable incident summary for Member 3's Report page.
        report_id == alert_id for simplicity (one report per alert).
        """
        alert = next((a for a in self.alerts if a.alert_id == alert_id), None)
        if not alert:
            return None
        response = next((r for r in self.responses if r.alert_id == alert_id), None)

        summary = (
            f"On {alert.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}, rule {alert.rule_id} "
            f"({alert.title}) fired with {alert.severity} severity for source IP "
            f"{alert.source_ip}. Evidence: {alert.reason}. "
        )
        if response:
            summary += (
                f"Simulated response action taken: {response.action} — "
                f"{response.description}."
            )
        else:
            summary += "No response action was recorded."

        return {
            "report_id": alert.alert_id,
            "alert": alert.to_dict(),
            "response": response.to_dict() if response else None,
            "summary": summary,
        }
